---
name: Clothes
version: 2.1.0
main: TungstenVn\Clothes\Clothes
api:
- 3.0.0
author: AntaxioYT
commands:
  clo:
    description: Open clothes menu Go subs AntaxioYT
  clothes:
    description: Open clothes menu Go subs AntaxioYT
...
